[project]
name = "qwen3-30b-realize"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "safetensors>=0.6.2",
    "torch>=2.9.0",
]
